Practical No. 03 - Implement Union, Intersection, Complement and
Difference operations on fuzzy sets. Also
create fuzzy relations by Cartesian product of any two fuzzy sets and
perform max-min
composition on any two fuzzy relations.

In [1]:
import numpy as np

In [2]:
def fuzzy_union(A,B):
    return np.maximum(A,B)

In [3]:
def fuzzy_intersection(A,B):
    return np.minimum(A,B)

In [4]:
def fuzzy_complement(A):
    return 1 - A

In [5]:
def fuzzy_diffrence(A,B):
    return np.maximum(A,1 - B)

In [6]:
def cartesian_product(A,B):
    return np.outer(A,B)

In [7]:
def max_min_compositions(R,S):
    return np.max(np.minimum.outer(R,S),axis = 1)

In [8]:
A =np.array([0.2,0.4,0.6,0.8])
B =np.array([0.3,0.5,0.7,0.9])

In [9]:
union_result = fuzzy_union(A,B)
intersection_result = fuzzy_intersection(A,B)
complement_A = fuzzy_complement(A)
diffrence_result = fuzzy_diffrence(A,B)
print("Union:",union_result)
print("Intersection:",intersection_result)
print("Complement of A:",complement_A)
print("Diffrence:",diffrence_result)

Union: [0.3 0.5 0.7 0.9]
Intersection: [0.2 0.4 0.6 0.8]
Complement of A: [0.8 0.6 0.4 0.2]
Diffrence: [0.7 0.5 0.6 0.8]


In [10]:
R = np.array([0.2, 0.5, 0.4]) # Fuzzy relation R
S = np.array([0.6, 0.3, 0.7]) # Fuzzy relation S

In [11]:
# Cartesian product of fuzzy relations
cartesian_result = cartesian_product(R, S)

In [12]:
# Max-Min composition of fuzzy relations
composition_result = max_min_compositions(R, S)

In [13]:
print("Cartesian product of R and S:")
print(cartesian_result)

Cartesian product of R and S:
[[0.12 0.06 0.14]
 [0.3  0.15 0.35]
 [0.24 0.12 0.28]]


In [14]:
print("Max-Min composition of R and S:")
print(composition_result)

Max-Min composition of R and S:
[0.2 0.5 0.4]
